---
- name: (RedHat 7) Install Remi repo
  package:
    name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    state: present
  when: ansible_distribution_major_version == "7"

- name: (RedHat 7) Install Redis
  package:
    name: "{{ redis_packages }}"
    enablerepo: "remi"
    state: present
  register: redis_installed
  when: ansible_distribution_major_version == "7"
